monogame-projektname: Run checks on incoming PR

on:
  pull_request:
    branches: [master, release, develop]

  # allow running this workflow manually
  workflow_dispatch:

jobs:
  android-build-check:
    runs-on: windows-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

    - name: Build projekt
      run: dotnet build monogame-projekt.csproj --configuration Release
